version: 0.1.{build}
image: Visual Studio 2017
configuration: Release


# Note: "Win32" rather than "x86" since Visual Studio uses Release|Win32
# and not Release|x86
platform:
	- Win32
	- x64

# Version check
init:
- cmd: >-
	cmake --version
	msbuild /version

# Recursive clone
install:
- cmd: git submodule update --init --recursive

# Configure platform 
before_build:
- cmd: >-
	mkdir build
	cd build
	if "%platform%"=="Win32" set CMAKE_GENERATOR_NAME="Visual Studio 15 2017"
	if "%platform%"=="x64" set CMAKE_GENERATOR_NAME="Visual Studio 15 2017 Win64"
	cmake -G %CMAKE_GENERATOR_NAME% -DCMAKE_BUILD_TYPE=%configuration% ..

build:
	project: build/SaiThumbs.sln
	parallel: true
	verbosity: normal

artifacts:
	- path: build/bin