version: 0.1.{build}-{branch}
image: Visual Studio 2017
configuration: Release

branches:
    only:
    - master
    - develop

# Note: "Win32" rather than "x86" since Visual Studio uses Release|Win32
# and not Release|x86
platform:
    - Win32
    - x64

# Recursive clone
install:
    - cmd: git submodule update --init --recursive

# Configure platform 
before_build:
    - cmd: mkdir build
    - cmd: cd build
    - cmd: if "%platform%"=="Win32" set CMAKE_GENERATOR_NAME="Visual Studio 15 2017"
    - cmd: if "%platform%"=="x64" set CMAKE_GENERATOR_NAME="Visual Studio 15 2017 Win64"
    - cmd: cmake -G %CMAKE_GENERATOR_NAME% -DCMAKE_BUILD_TYPE=%configuration% ..

build:
    project: build/SaiThumbs.sln
    parallel: true
    verbosity: normal

after_build:
    - cmd: 7z a SaiThumbs-%platform%.zip %APPVEYOR_BUILD_FOLDER%/build/bin/*.dll %APPVEYOR_BUILD_FOLDER%/build/bin/*.bat

artifacts:
    - path: SaiThumbs-%platform%.zip